In [1]:
print("helo")

[1] "helo"


In [2]:
print(23.9+11)

[1] 34.9


In [3]:
mean(1:5)

[1] 3

In [5]:
help("mean")

In [10]:
apple <- c('red','blue','orange')

In [7]:
apple

[1] "red"    "blue"   "orange"

In [8]:
print(class(apple))

[1] "character"


In [12]:
list1 <- list(c(2,5,3),21.3,sin) 

In [13]:
list1

[[1]]
[1] 2 5 3

[[2]]
[1] 21.3

[[3]]
function (x)  .Primitive("sin")

In [14]:
M = matrix(c('a','b','b','c','b','a'),nrow=2,ncol=3,byrow=TRUE)

In [15]:
M


[,1] [,2] [,3]
[1,] a    b    b   
[2,] c    b    a

In [16]:
a <- array(c('green','yellow'),dim=c(2,3,3))

In [18]:
print(a)

, , 1

     [,1]     [,2]     [,3]    
[1,] "green"  "green"  "green" 
[2,] "yellow" "yellow" "yellow"

, , 2

     [,1]     [,2]     [,3]    
[1,] "green"  "green"  "green" 
[2,] "yellow" "yellow" "yellow"

, , 3

     [,1]     [,2]     [,3]    
[1,] "green"  "green"  "green" 
[2,] "yellow" "yellow" "yellow"



In [19]:
apple_colors <- c('green','green','yellow','red','red','red')

In [20]:
apple_colors

[1] "green"  "green"  "yellow" "red"    "red"    "red"

In [21]:
factor_apple <- factor(apple_colors)

In [22]:
factor_apple

[1] green  green  yellow red    red    red   
Levels: green red yellow

In [23]:
v<- c(2,5.5,6)
t<-c(8,3,4)
print(v+t)
print(v-t)
print(v*t)

[1] 10.0  8.5 10.0
[1] -6.0  2.5  2.0
[1] 16.0 16.5 24.0


In [2]:
v <- readline()
v <- strsplit(v," ")

 3 2 1 3 4


In [3]:
v

[[1]]
[1] "3" "2" "1" "3" "4"

In [4]:
class(v)

[1] "list"

In [5]:
v <- c(v)

In [6]:
v

[[1]]
[1] "3" "2" "1" "3" "4"

In [7]:
class(v)

[1] "list"

In [8]:
class(c(v))

[1] "list"

In [12]:
#x <- readline()
v <- as.integer(v[[1]])

In [13]:
v

[1] 3 2 1 3 4

In [40]:
class(v)

[1] "list"

In [41]:
class(x)

[1] "integer"

In [49]:
for(i in 1:length(x)){
    print(x[i])
}

[1] 3
[1] 2
[1] 4
[1] 5
[1] 1
