# 1806554 Ganesh Bhandarkar (DA LAB)

# 1

In [16]:
x <- c(1,2,3,4,5)
print(sqrt(x))

[1] 1.000000 1.414214 1.732051 2.000000 2.236068


In [19]:
x <- c(11,23,12,14,4)
paste("min :",min(x))
paste("max :",max(x))
paste("sum :",sum(x))

[1] "min : 4"

[1] "max : 23"

[1] "sum : 64"

# 2

In [37]:
row_names = c("row1", "row2", "row3", "row4")
col_names = c("col1", "col2", "col3")
M = matrix(c(1:12), nrow = 4,ncol = 3, byrow = TRUE, dimnames = list(row_names, col_names))
print("Original Matrix:")
print(M)

[1] "Original Matrix:"
     col1 col2 col3
row1    1    2    3
row2    4    5    6
row3    7    8    9
row4   10   11   12


In [39]:
print(M[1,])

col1 col2 col3 
   1    2    3 


In [40]:
print(M[3,])

col1 col2 col3 
   7    8    9 


In [41]:
print(M[,2])

row1 row2 row3 row4 
   2    5    8   11 


# 3

In [21]:
v1 <- c(5,9,3)
v2 <- c(10,11,12,13,14,15)
result <- array(c(v1,v2),dim = c(3,3,2))

In [23]:
print(result)

, , 1

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15

, , 2

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15



In [24]:
print(result[3,,2])

[1]  3 12 15


In [25]:
print(result[1,3,1])

[1] 13


In [28]:
print(result[,,2])

     [,1] [,2] [,3]
[1,]    5   10   13
[2,]    9   11   14
[3,]    3   12   15


In [29]:
print(result[,,1]+result[,,2])

     [,1] [,2] [,3]
[1,]   10   20   26
[2,]   18   22   28
[3,]    6   24   30


# 4

In [60]:
players <- data.frame(
  player_no = c(1:5),
  name = c("Ganesh","Messi","Michael","Rohit","Ronnie"),
  age = c(17,31,37,29,48),
  profession= c("Sprinter","Footballer","Basketball","Cricketer","Snooker"),
  grade = c("C","A","B","A","A+")
)


result <- data.frame(players$name,players$grade)

print(result)

  players.name players.grade
1       Ganesh             C
2        Messi             A
3      Michael             B
4        Rohit             A
5       Ronnie            A+


In [61]:
result1 <- players[1:3,]
print(result1)

  player_no    name age profession grade
1         1  Ganesh  17   Sprinter     C
2         2   Messi  31 Footballer     A
3         3 Michael  37 Basketball     B


In [62]:
result <- players[c(2,5),c(1,3)]
print(result)

  player_no age
2         2  31
5         5  48
