# 1806554 Test (R Language) DA Lab

# 1

### a

In [50]:
A <- matrix( c(1,5,-2,1,2,-1,3,6,-3),nrow=3)
print(A)
print(A %*% A %*% A)

     [,1] [,2] [,3]
[1,]    1    1    3
[2,]    5    2    6
[3,]   -2   -1   -3
     [,1] [,2] [,3]
[1,]    0    0    0
[2,]    0    0    0
[3,]    0    0    0


### b

In [42]:
A[,3] <- A[,2]+A[,3]
print(A)

     [,1] [,2] [,3]
[1,]    1    1    4
[2,]    5    2    8
[3,]   -2   -1   -4


# 2


In [35]:
tmpFn <- function(x){
    n <- length(x)
    (x[1:(n-2)]+x[2:(n-1)]+x[3:n])/3
}
round(tmpFn(c(1:5,6:1)),2)

[1] 2.00 3.00 4.00 5.00 5.33 5.00 4.00 3.00 2.00

# 3

### a

In [47]:
empiricalCopula <- function(u,v,xVec,yVec){
n <- length(xVec)
rVecN <- rank(xVec)/(n+1)
sVecN <- rank(yVec)/(n+1)
sum((rVecN <= u)&(sVecN <= v))/n
}
empiricalCopula(c(0,1),c(0,1),c(7,3,1,4),c(4,2,1,3))

[1] 0.5

### b

In [48]:
empiricalCopula <- function(u,v,xVec,yVec){
n <- length(xVec)
rVecN <- rank(xVec)/(n+1)
sVecN <- rank(yVec)/(n+1)
valuesN <- colSums(outer(rVecN,u,"<=")&outer(sVecN,v,"<="))
cbind( uCoord = u, vCoord = v, empCop=valuesN/n )
}
empiricalCopula(c(0,1),c(0,1),c(7,3,1,4),c(4,2,1,3))

uCoord vCoord empCop
[1,] 0      0      0     
[2,] 1      1      1

# 4

In [51]:
print(outer(0:4,0:4,'+'))

     [,1] [,2] [,3] [,4] [,5]
[1,]    0    1    2    3    4
[2,]    1    2    3    4    5
[3,]    2    3    4    5    6
[4,]    3    4    5    6    7
[5,]    4    5    6    7    8


In [4]:
v <- c(1,2,3,4)
x <- c[5:8]
v*x[[1]]

NameError: name 'v' is not defined